blog/urls.py
from django.urls import path
from blog import views
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

app_name = 'blog'

urlpatterns = [
    path('', views.test, name='test'),
    path('<int:blog_id>/', views.detail, name='detail'),

]
# we have to import static, this functinality from Django project which we have import here.

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# search django media tutorial can help finding on web

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
    
]

# we have to import static, this functinality from Django project which we have import here.
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# # search django media tutorial can help finding on web

blog/models.py
from django.db import models

class all_blog(models.Model):
    title = models.CharField(max_length=100)
    description= models.TextField(max_length=500)
    date = models.DateField(auto_now=False)
    image = models.ImageField(upload_to='media/blog/images/', blank=True)
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description= models.CharField(max_length=250)
    image = models.ImageField(upload_to='media/portfolio/images/')
    url = models.URLField(blank=True) #this mean url is not a neccassry field, by default blank is fals(hence mandatory)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import all_blog

def test(request):
    egg = all_blog.objects.order_by('-date')
    return render(request, 'blog/all_blogs.html', {'bon':egg})

def detail(request, blog_id):
    jon = get_object_or_404(all_blog, pk=blog_id)
    return render(request, 'blog/detail.html',{'bobby':jon})

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects':projects})

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}
{% block content %}

<br><br>
<h1>Mustafiz's Blog</h1>
<h2>Mustafiz has written {{ bon.count }} blog{{ bon.count|pluralize }} </h2>

{% for egg in bon %}

<a href="{% url 'blog:detail' egg.id %}"><h2>{{ egg.title }}</h2></a>
<h3>{{ egg.date|date:'M d Y'|upper }}</h3>
<p>{{ egg.description|striptags|truncatechars:50 }}</p>
{% if egg.image %}
<img src="{{ egg.image.url }}">
{% endif %}
{% if egg.url %}
<br><a href="{{ egg.url}}">Link</a>
{% endif %}
{% endfor %}

{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}
{% block content %}

<h1>{{ bobby.title }}</h1>
<h2>--{{ bobby.date|date:'F jS Y'}}--</h2>

{{ bobby.description|safe }}

{% endblock %}

portfolio/templates/portfolio/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Mustafiz's Portfolio</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>        
   
{% block content %}{% endblock %}

    
<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% block content %}

<h1>Mustafiz's Portfolio</h1>

{% load static %}

<a href="{% url 'blog:test' %}">Blog</a>
<br>
<a href="{% static 'portfolio\ccna.pdf' %}">Resume</a>
<br>
<img src="{% static 'portfolio\original-paddle.jpg' %}" height="500" width="300">

{% for project in projects %}

<h2>{{ project.title }}</h2>
<p>{{ project.description }}</p>
<img src="{{ project.image.url }}">
{% if project.url %}
<br><a href="{{ project.url}}">Link</a>
{% endif %}
{% endfor %}

{% endblock %}